In [4]:
# 1
import numpy as np
np.__version__


'1.20.1'

In [2]:
import numpy as np
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Administrator/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Administrator/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Administrator/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Administrator/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Administrator/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Administrator/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Administrator/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Administrator/anaconda3\\Library

In [6]:
# 9
a = np.matrix(np.arange(12,21).reshape(3,3))
print(a)
print(type(a))

[[12 13 14]
 [15 16 17]
 [18 19 20]]
<class 'numpy.matrix'>


In [7]:
# 9
a = np.arange(12,21).reshape(3,3)
print(a)
print(type(a))

[[12 13 14]
 [15 16 17]
 [18 19 20]]
<class 'numpy.ndarray'>


In [16]:
# 13
a = np.random.random((9,9))
print(a.min(), a.max())

0.007493812515301901 0.9821587572153087


In [18]:
# 24
Z1 = np.matrix(np.random.random([6,3]))
Z2 = np.matrix(np.random.random([3,4]))
print(np.dot(Z1,Z2))

[[1.06921695 0.68334844 0.59256019 0.5066581 ]
 [0.78406286 0.80004686 0.97295628 0.5673989 ]
 [1.13293272 0.87909866 0.94154744 0.6746947 ]
 [0.99527238 0.99155897 1.10818633 0.61647171]
 [1.59786346 1.24829815 1.26006826 0.86965261]
 [1.05051254 1.12832318 1.27017145 0.65504284]]


In [52]:
#37. Create a 3x3 matrix with row values ranging from 0 to 2 (★★☆)

In [51]:
#44
a=np.array(np.arange(5).reshape(1,5))
print(a)
b=np.argmax(a)
a[0,b]=0
print(a)

[[0 1 2 3 4]]
[[0 1 2 3 0]]
