In [6]:
import numpy as np
a = np.array([[1,2],[4,5],[7,8]])
print(a)

[[1 2]
 [4 5]
 [7 8]]


In [9]:
my_matrix = [[1,2],[4,5],[7,8]]
my_matrix
np.array(my_matrix)

array([[1, 2],
       [4, 5],
       [7, 8]])

In [21]:
a = np.zeros((5,6))
b=np.ones((1,6))
c=np.ones((3,3))
c=c*9
c[1,1]=6
a[1:4,2:5]=c
a[1:5,1]=1
a[4:]=1
print(a)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 9. 9. 9. 0.]
 [0. 1. 9. 6. 9. 0.]
 [0. 1. 9. 9. 9. 0.]
 [1. 1. 1. 1. 1. 1.]]


In [22]:
b[1:0,1:0:]=[[4,4],[6,6],[11,11]]

ValueError: could not broadcast input array from shape (3,2) into shape (0,0)

In [23]:
a1 = np.array([[9,11],[1,7],[15,60]]) #2D
a2 = np.array([[3,6],[6,5],[1,16]]) #2D
a3 = np.array([3,6,9]) #1D

# substract array a1 from a2 with axis=1
print(a2-a1) # axis = 0

# dot multiplication of: (a1 dot a2) dot a3

[[ -6  -5]
 [  5  -2]
 [-14 -44]]


In [26]:
print(np.sum(a2-a1,axis=1))

[-11   3 -58]


In [27]:
print(np.sum(a2-a1,axis=0))

[-15 -51]


In [1]:
import random
import string
def random_user_id():
    return ''.join(random.sample(string.ascii_letters + string.digits, 6))
print(random_user_id())

dI5ecS


In [3]:
a=int(input("pls enter how many ID u want"))
b=int(input("pls enter how many letters u want in a single ID"))
def user_id_gen_by_user():
    c=[random.sample(string.ascii_letters + string.digits, b) for i in range(a)]
    for l in c:
        print(''.join(l))
user_id_gen_by_user()

pls enter how many ID u want5
pls enter how many letters u want in a single ID8
Fo1iueWf
jTqDoI9S
K0zt9eGa
7sTXZewN
UwBTexc1


In [7]:
def rgb_color_gen():
    return [random.randint(0,255),random.randint(0,255),random.randint(0,255)]
print(rgb_color_gen())

[41, 3, 126]


In [10]:
def list_of_hexa_colors():
    letter=["1","2","3","4","5","6","7","8","9","0","a",'b','c','d','e','f']
    hex="#"+"".join(random.sample(letter,6))
    return hex
print(list_of_hexa_colors())

#ab7f8c


In [14]:
def list_of_rgb_colors():
    return(random.randint(0,255),random.randint(0,255),random.randint(0,255))
print(list_of_rgb_colors())

(29, 168, 173)


In [19]:
def generate_colors(input,times):
    list=[]
    if input == 'hexa':
        while times != 0:
            list.append(list_of_hexa_colors())
            times-=1
        return list
    elif input =='rgb':
        while times != 0:
            list.append(list_of_rgb_colors())
            times -= 1
        return list
    else:
        print("error")
print(generate_colors('hexa',3))
print(generate_colors('hexa',1))
print(generate_colors('rgb',1))
print(generate_colors('rgb',3))

['#3d7840', '#8d27ca', '#962c4f']
['#49cb8d']
[(123, 242, 88)]
[(57, 36, 107), (52, 65, 252), (77, 124, 19)]


In [22]:
def shuffle_list(seq) :
    return random.shuffle(seq)

def func():
    num = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0"]
    return random.sample(num,6)
print(func())

['1', '6', '2', '9', '5', '4']
